### Request all credentials
GET http://localhost:3300/api/coursedata HTTP/1.1
Accept: application/json



### Add a new credential
POST http://localhost:3300/api/coursedata HTTP/1.1
Content-Type: application/json

{
  "service": "Test2",
  "username": "Test2",
  "password": "Test2"
}